### ISSUE TITLE
List widget order by i18n fields

### ISSUE THREAD

**Issue by eXtreme** [diem-project/diem#107]
I have:

```
News: 
  actAs:
    I18n:
      actAs:
        Timestampable:
        DmVersionable:
```

I want to sort my news in list widget by created_at field of I18n, but there is only "Id" field available.
