### ISSUE TITLE
DmGallery behavior does not work as a child of I18n

### ISSUE THREAD

**Issue by eXtreme** [diem-project/diem#123]
```
Foobar:
    actAs:
        I18n:
            actAs:
                DmGallery:
```

DmGallery does not show up for records in admin. Manual adding DmGallery to generator.yml gives errors.
