### ISSUE TITLE
Empty admin edit forms with Concrete inheritance and i18n

### ISSUE THREAD

**Issue by eXtreme** [diem-project/diem#210]
I have a `TextItem` model witch actAs `I18n` and has some columns. Models `News` and `Text` inherit from `TextItem` with Concrete Inheritance.

Admin list page and advanced search (aka filter) form show fields, but when I want to add or edit a record, the form is empty, to be more precise - **there are no fields**. 

My schema:

```
TextItem:
  actAs:
    I18n:
      fields: [title, excerpt, content, is_available]
  columns:
    title: { type: string(255), notnull: true }
    excerpt: { type: clob, notnull: true, extra: markdown }
    content: { type: clob, extra: markdown }
    is_available: { type: boolean }

News:
  inheritance:
    extends: TextItem
    type: concrete

Text:
  inheritance:
    extends: TextItem
    type: concrete
```

diem 5.1
