### ISSUE TITLE
Admin filtration - always invalid filter forms

### ISSUE THREAD

**Issue by antitoxic** [diem-project/diem#380]
I've just tested the admin filtration. There was a bug that forced filter forms to be always invalid. This is Diem related. I've tested it with the latest symfony. Works fine. I even **deducted a fix** out of my testing.

This is what diem does in BaseForms right now is :

```
$this->setValidator('price', new sfValidatorNumber(array('required' => false)));
```

This is what Diem should do

```
$this->setValidator('price', new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))));
```

I've seen this in bare symfony project. I guess the changes should be made in **sfDoctrineFormFilterGeneratedTemplate** or relevant or other similar files.

Also the **enum** fields (like `type` in the given schema below) must not have `'multiple' => true` in their widgets.

Schema is not relevant but for anyone that want it:

```
BeautyProcedure:
    actAs:
        Timestampable:
    columns:
        scheduled_at:
            type: time
        type:
            type: enum
            values: [ cat1, cat2, cat3]
        client_id:
            type: integer
        staff_member_id:
            type: integer
        duration:
            type: time
        price:
            type: float
    relations:
        Client:
            class:      StudioClient
            local:      client_id
            onDelete:   RESTRICT # Client can't be deleted if the procedure is existing
        StaffMember:
            class:      StaffMember
            local:      staff_member_id
            onDelete:   RESTRICT # Stuff Member can't be deleted if the procedure is existing
        RelatedProcedures:
            class: BeautyProcedure
            local: beauty_procedure_origin
            foreign: beauty_procedure_seconded
            refClass: RelatedBeautyProcedureReference
            equal: true

RelatedBeautyProcedureReference:
    columns:
        beauty_procedure_origin:
            type: integer
            primary: true
        beauty_procedure_seconded:
            type: integer
            primary: true
StudioClient:
    columns:
        name:
            type: string(255)
            notnull: true
StaffMember:
    columns:
        name:
            type: string(255)
            notnull: true
```
